from pydantic import BaseModel, Field
from typing import List

class TextInput(BaseModel):
    text_list: List[str] = Field(
        example=[
        "In brain cells, brain tumors can be identified as unnatural and unregulated development. Consequently, as the person’s cranium is hard and capacity bounded, any sudden development will affect human functions based on the portion of the brain involvement and the cancer may also spread to other parts of the body. As stated by WHO, World Cancer Report; Cerebrum disease represents under 2% of human malignant growth; anyway, serious toxicity and complicacy are generated (B. W. Stewart 2014). In the United Kingdom, It is estimated that annually around 5,250 deaths are recorded due to actions of brain, Central Nervous System (CNS), and other intracranial tumors (Brain, 2019).", 
        "Brain tumors can be grouped in a variety of methods, including major, minor tumors. About 70% of all mind malignant growths are essential tumors, while 30% are auxiliary tumors. This classification is based on the origin of tumors; for example, primary tumors are those that begin in the brain. Tumors, then again, start in another piece of the body and afterward spread to the mind, most of which are guileful (A. Behin, 2003). Brain tumors can be detected using a variety of imaging methods. Diffusion tensor imaging (DTI) and Magnetic resonance imaging (MRI) are two minimally invasive diagnostic procedures. Rather than ionizing radiation, a MRI examine utilizes non-intrusive difference specialists and an assortment of imaging boundaries, two of which are more explicit in delicate tissue (A.Drevelegas, 2007; G. Litjens, 2017).", 
        "Gliomas are the extremely well-known kind of cerebrum tumor that begin in the glial cells of the mind (M. L.Goodenberger, 2012). Gliomas are available in 30% of all brain and central nervous system tumors and in 80% of threatening cerebrum tumors. Gliomas are arranged by the World Health Organization into four sorts, going from type I to type IV (D. N. Louis, 2016). Evaluation I tumors are non malignant and have a surface that is fairly near that of typical glial cells, grade II tumors have a surface that is generously unique, grade III tumors are malignant with unusual tissue appearance, and grade IV tumors have the most serious level of unaided eye representation of gliomas and tissue defects (L. M. De Angelis, 2001). Meningioma is a considerate tumor that grows gradually inside the human skull on the layer that covers the brain and spinal cord. Most of meningioma tumors are non malignant (D. N. Louis, 2016). Nonetheless, the pituitary tumor begins with the pituitary glands, which control hormone production and body functions. It is common for it to be benign, bone-expanding, or malignant."
        ]
    )